app/blueprints/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__, template_folder='templates')

from . import routes

app/blueprints/main/routes.py
from flask import (render_template, flash,
                   redirect, url_for, request, jsonify,
                   session)

from app.extensions import db
from app.forms import (LoginForm, RegistrationForm)
from flask_login import (current_user, login_user,
                         logout_user, login_required)
import sqlalchemy as sa
from urllib.parse import urlsplit
from app.models import User, Word, WordGroup, Definition
from typing import cast


from . import main_bp


@main_bp.route('/',  methods=['GET', 'POST'])
@main_bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('index.html', title='Home')


@main_bp.route('/user/<username>')
@login_required
def user(username):
    query = sa.select(WordGroup).where(
        cast("ColumnElement[bool]", WordGroup.user_id == current_user.id)).order_by(sa.desc(WordGroup.created_at))
    word_groups = db.session.scalars(query).all()
    return render_template('user.html', word_groups=word_groups)


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.email == form.email.data))
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or urlsplit(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/blueprints/main/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex align-items-center justify-content-center">
    <div class="container text-center" style="max-width: 400px;">
        <h1 class="mb-4">Hi, {{ current_user.username }}!</h1>
        <div class="d-flex flex-column">
            <a href="{{ url_for('word_groups.learn_group') }}" class="btn btn-outline-primary mb-2">Learn words</a>
            <a href="{{ url_for('word_groups.see_group_results') }}" class="btn btn-outline-primary mb-2">Improve learned</a>
            <a href="{{ url_for('word_groups.group_formation') }}" class="btn btn-outline-primary mb-2">Create new group</a>
            <a href="{{ url_for('word_groups.see_all_words') }}" class="btn btn-outline-primary mb-2">See all words</a>
        </div>
    </div>
</div>
{% endblock %}

app/blueprints/main/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex align-items-center justify-content-center">
  <main class="form-signin" style="max-width: 400px; width: 100%;">
    <form method="post" action="{{ url_for('main.login') }}">
      {{ form.hidden_tag() }}
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

      <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingInput", placeholder="name@example.com") }}
        <label for="floatingInput">Email address</label>
        {% for error in form.email.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>

      <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder="Password") }}
        <label for="floatingPassword">Password</label>
        {% for error in form.password.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>

      <div class="form-check text-start my-3">
        {{ form.remember_me(class="form-check-input", id="flexCheckDefault") }}
        <label class="form-check-label" for="flexCheckDefault">
          Remember me
        </label>
      </div>
      {{ form.submit(class="btn btn-primary w-100 py-2") }}
      <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
    </form>
  </main>
</div>
{% endblock %}

app/blueprints/main/templates/register.html
{% extends "base.html" %}


{% block content %}
<div class="d-flex align-items-center justify-content-center">
  <main class="form-signin" style="max-width: 400px; width: 100%;">
    <form method="post" action="{{ url_for('main.register') }}">
      {{ form.hidden_tag() }}
      <h1 class="h3 mb-3 fw-normal">Register</h1>

      <div class="form-floating mb-3">
        {{ form.username(class="form-control", id="floatingInput", placeholder="Name") }}
        <label for="floatingInput">Name</label>
      </div>

      <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingInput", placeholder="name@example.com") }}
        <label for="floatingInput">Email address</label>
        {% for error in form.email.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>

      <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder="Password") }}
        <label for="floatingPassword">Password</label>
        {% for error in form.password.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>

      <div class="form-floating mb-3">
        {{ form.password2(class="form-control", id="floatingPassword", placeholder="Repeat password") }}
        <label for="floatingPassword">Password</label>
        {% for error in form.password.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      {{ form.submit(class="btn btn-primary w-100 py-2") }}
      <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2024</p>
    </form>
  </main>
</div>
{% endblock %}

app/blueprints/main/templates/user.html
{% extends "base.html" %}

{% block content %}
<main>
<div class="container">
  <h1>{{ current_user.username }}'s word groups</h1>
    <div class="row mb-3 text-center">
    <div class="col-2 themed-grid-col-top">word</div>
    <div class="col-2 themed-grid-col-top">part_of_speech</div>
    <div class="col-8 themed-grid-col-top">definition</div>
  </div>
  {% for group in word_groups %}
    <div class="row">
<!--      <h2>{{ group.name }}</h2>-->
        <p><b>group: {{ group.id }}</b></p>
      <div>
        {% for definition in group.words_definitions %}
          <div class="row mb-3 text-center">
            <div class="col-2 themed-grid-col">{{definition.word_text}}</div>
            <div class="col-2 themed-grid-col">{{definition.part_of_speech}}</div>
            <div class="col-8 themed-grid-col">{{definition.text}}</div>
          </div>
        {% endfor %}
        <div class="row">
          <p>match definitions: {{ group.points_ratio_math_definitions }}</p>
          <p>fill gaps: {{ group.points_ratio_fill_gaps }}</p>
        </div>
        <div class="row">
            <div class="col">
              <form action="{{ url_for('tasks.task_match_definitions', group_id=group.id) }}" class="d-inline">
                <input type="hidden" name="group_id" value="{{ group.id }}">
                <button type="submit" name="action" value="learn" class="btn btn-primary">Learn</button>
              </form>
              <form action="{{ url_for('tasks.task_fill_the_gaps', group_id=group.id) }}" class="d-inline">
                <input type="hidden" name="group_id" value="{{ group.id }}">
                <button type="submit" name="action" value="fill in the gaps" class="btn btn-primary">Task gaps</button>
              </form>
              <form action="{{ url_for('tasks.task_ccqs', group_id=group.id) }}" class="d-inline">
                <input type="hidden" name="group_id" value="{{ group.id }}">
                <button type="submit" name="action" value="CCQS" class="btn btn-primary">CCQS</button>
              </form>
              <form action="{{ url_for('tasks.task_match_definitions', group_id=group.id) }}" class="d-inline">
                <input type="hidden" name="group_id" value="{{ group.id }}">
                <button type="submit" name="action" value="match definitions" class="btn btn-secondary">See</button>
              </form>
              <form action="{{ url_for('word_groups.mpf', group_id=group.id) }}" class="d-inline">
                <input type="hidden" name="group_id" value="{{ group.id }}">
                <button type="submit" name="action" value="mpf" class="btn btn-secondary">See</button>
              </form>
            </div>
          </div>
      <p>from: {{ group.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</p>
    </div>
  {% endfor %}
</div>
</main>
{% endblock %}